#' Identify individuals contained within a quadrat
#'
#' Given a spatially explicit data frame of individual locations in a simulated arena,
#' and the bounds of a series of quadrats, identifies the contents of each quadrat.
#'
#' @param positions Data frame of three columns: "individuals", "X", and "Y"
#' @param quadrat_bounds Matrix of X Y coordinates of quadrats
#' 
#' @details Takes a data frame like that returned from locationSampler(), and a matrix
#' like that returned from quadratPlacer(), and returns the resulting community data
#' matrix such as might be generated by someone surveying a forest plot. There is a check
#' added so that if any quadrat has < 2 species the function returns FALSE. There is
#' probably a better way to do this, but this works.
#'
#' @return A matrix with species as rows and quadrats as columns. Quadrats are unnamed
#'
#' @export
#'
#' @references Miller, Trisos and Farine.
#'
#' @examples
#' library(geiger)
#' library(colorRamps)
#'
#' temp <- phyloNtraits(50)
#'
#' scaled <- scaler(temp[[2]], min.arena=0, max.arena=300)
#'
#' phydistmatrix <- cophenetic(temp[[1]])
#'
#' #define a color for each species
#' cols <- blue2green2red(nrow(phydistmatrix))
#'
#' positions <- locationSampler(phyloNtraits.results=temp, scaled.results=scaled, mean.log.individuals=4, length.parameter=5000, sd.parameter=50)
#'
#' #plot the arena. don't close the window
#' plot(positions$X, positions$Y, pch=20, cex=0.5, xlim=c(0,300), ylim=c(0,300), col=cols[positions$individuals])
#'
#' bounds <- quadratPlacer(no.quadrats=15, x_max=300, y_max=300, quadrat_size=50)
#'
#' #plot the arena. don't close the window
#' plot(positions$X, positions$Y, pch=20, cex=0.5, xlim=c(0,300), ylim=c(0,300), col=cols[positions$individuals])
#'
#' quadratPlotter(bounds)
#'
#' #this community data matrix is not in picante format, use t()
#' temp.cdm <- quadratContents(positions, bounds)

quadratContents <- function(positions, quadrat_bounds)
{
	species <- unique(positions$individuals)
	com.results <- matrix(0, ncol=dim(quadrat_bounds)[1], nrow=length(species))
	rownames(com.results) <- species

	for (i in c(1:dim(quadrat_bounds)[1])) 
	{
		in_quadrat <- positions$individuals[positions$X >= quadrat_bounds[i,1] & positions$X <= quadrat_bounds[i,2] & positions$Y >= quadrat_bounds[i,3] & positions$Y <= quadrat_bounds[i,4]]

		for (j in c(1:length(species)))
		{
			com.results[j,i] <- sum(in_quadrat == species[j])
		}
	}

	##important check to make sure no quadrat has only a single species (or less in it)
	
	if(any(apply(com.results, 2, lengthNonZeros) <= 1))
	{
		print("Quadrat placed with < 2 species")
		com.results <- FALSE
	}

	return(com.results)
}
