#' Identify individuals contained within a quadrat
#'
#' Given a spatially explicit data frame of individual locations in a simulated arena,
#' and the bounds of a series of quadrats, identifies the contents of each quadrat.
#'
#' @param arena Data frame of three columns: "individuals", "X", and "Y"
#' @param quadratPlacer.results The results of a call to quadratPlacer. A list with two
#' elementers. The first is a matrix of X Y coordinates of quadrats. The second is a
#' symmetrical distance matrix summarizing the distances among these quadrats.
#' 
#' @details Takes a data frame like that returned from filteringArena(), and a matrix
#' like that returned from quadratPlacer(), and returns the resulting community data
#' matrix such as might be generated by someone surveying a forest plot. Quadrats with < 2
#' species are excluded from the CDM.
#'
#' @return A matrix with species as rows and quadrats as columns.
#'
#' @export
#'
#' @references Miller, E. T., D. R. Farine, and C. H. Trisos. 2015. Phylogenetic community
#' structure metrics and null models: a review with new methods and software.
#' bioRxiv 025726.
#'
#' @examples
#' library(colorRamps)
#'
#' tree <- sim.bdtree(b=0.1, d=0, stop="taxa", n=50)
#'
#' temp <- evolveTraits(tree)
#'
#' phydistmatrix <- cophenetic(temp[[1]])
#'
#' #define a color for each species
#' cols <- blue2green2red(nrow(phydistmatrix))
#'
#' #prep the data for the simulation
#' prepped <- prepSimulations(tree, arena.length=300, mean.log.individuals=2, 
#' length.parameter=5000, sd.parameter=50, max.distance=20, proportion.killed=0.2,
#' competition.iterations=3)
#'
#' singleArena <- filteringArena(prepped)
#'
#' #plot the arena. don't close the window
#' plot(singleArena$arena$X, singleArena$arena$Y, pch=20, cex=0.5, xlim=c(0,300), 
#'	ylim=c(0,300), col=cols[singleArena$arena$individuals])
#'
#' boundResults <- quadratPlacer(no.quadrats=10, arena.length=300, quadrat.length=50)
#'
#' quadratPlotter(boundResults$quadrat.bounds)
#'
#' #return a CDM in picante format
#' cdm <- quadratContents(singleArena$arena, boundResults)

quadratContents <- function(arena, quadratPlacer.results)
{
	species <- unique(arena$individuals)
	com.results <- matrix(0, ncol=dim(quadratPlacer.results$quadrat.bounds)[1], 
		nrow=length(species))
	rownames(com.results) <- species

	for (i in c(1:dim(quadratPlacer.results$quadrat.bounds)[1])) 
	{
		in_quadrat <- arena$individuals[arena$X >= 
			quadratPlacer.results$quadrat.bounds[i,1] & 
			arena$X <= quadratPlacer.results$quadrat.bounds[i,2] & 
			arena$Y >= quadratPlacer.results$quadrat.bounds[i,3] & 
			arena$Y <= quadratPlacer.results$quadrat.bounds[i,4]]

		for (j in c(1:length(species)))
		{
			com.results[j,i] <- sum(in_quadrat == species[j])
		}
	}

	#CDM was NOT IN PICANTE FORMAT. Transpose to picante
	com.results <- t(com.results)

	#now give the same temporary names as quadratPlacer.results to CDM so you can see what
	#needs to get cut from the distance matrix
	row.names(com.results) <- row.names(quadratPlacer.results$dists)
	
	#identify quadrats that have fewer than 2 species. pull their tempQuadrat ID.
	toCut <- row.names(com.results)[apply(com.results, 1, lengthNonZeros) < 2]
	
	#pull these quadrats out of the CDM and out of the dists object
	com.results <- com.results[!(row.names(com.results) %in% toCut),]
	#first rows of distance object
	quadratPlacer.results$dists <-
		quadratPlacer.results$dists[!(row.names(quadratPlacer.results$dists) %in% toCut),]
	#now columns of distance object
	quadratPlacer.results$dists <-
		quadratPlacer.results$dists[,!(colnames(quadratPlacer.results$dists) %in% toCut)]	
		
	#assign names to quadrats (note that this happens after removing quadrats with < 2 spp
	#so i believe the regional null should not have any trouble accidentally creating 
	#quadrats with different names. need to confirm and should make regional null require
	#existing quadrat names to avoid any conflicts
	
	quadrat <- paste("quadrat",1:dim(com.results)[1], sep="")
	dimnames(com.results)[[1]] <- quadrat

	#assign the same new names to the distance object
	row.names(quadratPlacer.results$dists) <- quadrat
	colnames(quadratPlacer.results$dists) <- quadrat
	
	results <- list("picante.cdm"=com.results, "dists"=quadratPlacer.results$dists)
	return(results)
}
