#' Identify individuals contained within a quadrat
#'
#' Given a spatially explicit data frame of individual locations in a simulated arena,
#' and the bounds of a series of quadrats, identifies the contents of each quadrat.
#'
#' @param arena Data frame of three columns: "individuals", "X", and "Y"
#' @param quadrat.bounds Matrix of X Y coordinates of quadrats, usually returned from
#' quadratPlacer()
#' 
#' @details Takes a data frame like that returned from filteringArena(), and a matrix
#' like that returned from quadratPlacer(), and returns the resulting community data
#' matrix such as might be generated by someone surveying a forest plot. Quadrats with < 2
#' species are excluded from the CDM.
#'
#' @return A matrix with species as rows and quadrats as columns.
#'
#' @export
#'
#' @references Miller, Trisos and Farine.
#'
#' @examples
#' library(geiger)
#' library(colorRamps)
#'
#' tree <- sim.bdtree(b=0.1, d=0, stop="taxa", n=50)
#'
#' temp <- evolveTraits(tree)
#'
#' scaled <- scaler(temp[[2]], min.arena=0, max.arena=300)
#'
#' phydistmatrix <- cophenetic(temp[[1]])
#'
#' #define a color for each species
#' cols <- blue2green2red(nrow(phydistmatrix))
#'
#' #prep the data for the simulation
#' prepped <- prepSimulations(tree, arena.length=300, mean.log.individuals=4, 
#' length.parameter=5000, sd.parameter=50, max.distance=20, proportion.killed=0.2,
#' competition.iterations=25)
#'
#' singleArena <- filteringArena(prepped)
#'
#' #plot the arena. don't close the window
#' plot(singleArena$arena$X, singleArena$arena$Y, pch=20, cex=0.5, xlim=c(0,300), ylim=c(0,300), 
#' col=cols[singleArena$arena$individuals])
#'
#' bounds <- quadratPlacer(no.quadrats=10, arena.length=300, quadrat.length=50)
#'
#' quadratPlotter(bounds)
#'
#' #return a CDM in picante format
#' cdm <- quadratContents(singleArena$arena, bounds)

quadratContents <- function(arena, quadrat.bounds)
{
	species <- unique(arena$individuals)
	com.results <- matrix(0, ncol=dim(quadrat.bounds)[1], nrow=length(species))
	rownames(com.results) <- species

	for (i in c(1:dim(quadrat.bounds)[1])) 
	{
		in_quadrat <- arena$individuals[arena$X >= quadrat.bounds[i,1] & 
			arena$X <= quadrat.bounds[i,2] & arena$Y >= quadrat.bounds[i,3] 
			& arena$Y <= quadrat.bounds[i,4]]

		for (j in c(1:length(species)))
		{
			com.results[j,i] <- sum(in_quadrat == species[j])
		}
	}

	#CDM was NOT IN PICANTE FORMAT. Transpose to picante
	com.results <- t(com.results)

	#if a quadrat has fewer than 2 species in it, exclude from further analysis
	
	com.results <- com.results[apply(com.results, 1, lengthNonZeros) >= 2,]
	
	#assign names to quadrats (note that this happens after removing quadrats with < 2 spp
	#so i believe the regional null should not have any trouble accidentally creating 
	#quadrats with different names. need to confirm and should make regional null require
	#existing quadrat names to avoid any conflicts

	quadrat <- paste("quadrat",1:dim(com.results)[1], sep="")

	dimnames(com.results)[[1]] <- quadrat

	return(com.results)
}
