#' Run defined spatial simulations
#'
#' Given a prepared simulations.input object, will run all simulations defined in 
#' defineSimulations, and return a list of randomized CDMs.
#'
#' @param simulations.input A prepared simulations.input object, as generated by 
#' prepSimulations.
#' @param simulations Untested. It should be possible to provided a list of named
#' spatial simulations here, rather than needing to define them in defineSimulations. 
#' 
#' @details Currently we are running 3 spatial simulations. This function
#' first confirms that the input is of class simulations.input and, if so, then
#' confirms that the simulations are in a named list (via checkSimulations),
#' then lapplies all spatial simulation functions to the input object.
#'
#' @return A list of lists of simulation results, where each of the first-order elements
#' in the list relates to a unique simulation as defined in defineSimulations.
#'
#' @export
#'
#' @import phylobase grid ecoPDcorr
#'
#' @references Miller, Trisos and Farine.
#'
#' @export
#'
#' @references Miller, Trisos and Farine.
#'
#' @examples
#' library(geiger)
#'
#' tree <- sim.bdtree(b=0.1, d=0, stop="taxa", n=50)
#'
#' prepped <- prepSimulations(tree, arena.length=300, mean.log.individuals=4, 
#' length.parameter=5000, sd.parameter=50, max.distance=20, proportion.killed=0.2,
#' competition.iterations=3)
#'
#' results <- runSimulations(prepped)

runSimulations <- function(simulations.input, simulations=NULL)
{
	if(!inherits(simulations.input, "simulations.input"))
	{
		stop("Input needs to be of class 'simulations.input'")
	}
		
	simulations <- checkSimulations(simulations)
		
	results <- lapply(simulations, function(x) x(simulations.input))
	
	results
}
